// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from './server'

export type PageName = 'Error' | 'Sentences/Index' | 'Sentences/New' | 'Sentences/Show'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Error': unknown
    'Sentences/Index': unknown
    'Sentences/New': unknown
    'Sentences/Show': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
